// Code generated by gtag. DO NOT EDIT.
// See: https://github.com/wolfogre/gtag

//go:generate gtag -types User -tags bson .
package tutorial

import (
	"reflect"
	"strings"
)

var (
	valueOfUser = User{}
	typeOfUser  = reflect.TypeOf(valueOfUser)

	_                = valueOfUser.Id
	fieldOfUserId, _ = typeOfUser.FieldByName("Id")
	tagOfUserId      = fieldOfUserId.Tag

	_                  = valueOfUser.Name
	fieldOfUserName, _ = typeOfUser.FieldByName("Name")
	tagOfUserName      = fieldOfUserName.Tag

	_                   = valueOfUser.Email
	fieldOfUserEmail, _ = typeOfUser.FieldByName("Email")
	tagOfUserEmail      = fieldOfUserEmail.Tag
)

// UserTags indicate tags of type User
type UserTags struct {
	Id    string // `bson:"_id"`
	Name  string // `bson:"name"`
	Email string // `bson:"email"`
}

// Tags return specified tags of User
func (User) Tags(tag string, convert ...func(string) string) UserTags {
	conv := func(in string) string { return strings.TrimSpace(strings.Split(in, ",")[0]) }
	if len(convert) > 0 {
		conv = convert[0]
	}
	if conv == nil {
		conv = func(in string) string { return in }
	}
	_ = conv
	return UserTags{
		Id:    conv(tagOfUserId.Get(tag)),
		Name:  conv(tagOfUserName.Get(tag)),
		Email: conv(tagOfUserEmail.Get(tag)),
	}
}

// TagsBson is alias of Tags("bson")
func (v User) TagsBson() UserTags {
	return v.Tags("bson")
}
