// Code generated by gtag. DO NOT EDIT.
// See: https://github.com/wolfogre/gtag

//go:generate gtag -types User,Empty,UserName,UserName .
package regular

import "reflect"

var (
	valueOfEmpty = Empty{}
	typeOfEmpty  = reflect.TypeOf(valueOfEmpty)
)

type EmptyTags struct {
}

func (Empty) Tags(tag string) EmptyTags {
	return EmptyTags{}
}

func (v Empty) TagsJson() EmptyTags {
	return v.Tags("json")
}

func (v Empty) TagsBson() EmptyTags {
	return v.Tags("bson")
}
