// Code generated by gtag. DO NOT EDIT.
// See: https://github.com/wolfogre/gtag

//go:generate gtag -types User,Empty,UserName,UserName ../../test/internal/regular/
package regular

import "reflect"

var (
	valueOfEmpty = Empty{}
	typeOfEmpty  = reflect.TypeOf(valueOfEmpty)
)

type EmptyTags struct {
}

func (Empty) Tags(tag string) EmptyTags {
	return EmptyTags{}
}
