// Code generated by gtag. DO NOT EDIT.
// See: https://github.com/wolfogre/gtag

//go:generate gtag -types Empty,User,UserName -tags bson,json .
package regular

import "reflect"

var (
	valueOfUser = User{}
	typeOfUser  = reflect.TypeOf(valueOfUser)

	_                = valueOfUser.Id
	fieldOfUserId, _ = typeOfUser.FieldByName("Id")
	tagOfUserId      = fieldOfUserId.Tag

	_                  = valueOfUser.Name
	fieldOfUserName, _ = typeOfUser.FieldByName("Name")
	tagOfUserName      = fieldOfUserName.Tag

	_                   = valueOfUser.Email
	fieldOfUserEmail, _ = typeOfUser.FieldByName("Email")
	tagOfUserEmail      = fieldOfUserEmail.Tag

	_                 = valueOfUser.age
	fieldOfUserage, _ = typeOfUser.FieldByName("age")
	tagOfUserage      = fieldOfUserage.Tag
)

type UserTags struct {
	Id    string
	Name  string
	Email string
	age   string
}

func (User) Tags(tag string) UserTags {
	return UserTags{
		Id:    tagOfUserId.Get(tag),
		Name:  tagOfUserName.Get(tag),
		Email: tagOfUserEmail.Get(tag),
		age:   tagOfUserage.Get(tag),
	}
}

func (v User) TagsBson() UserTags {
	return v.Tags("bson")
}

func (v User) TagsJson() UserTags {
	return v.Tags("json")
}

var (
	valueOfUserName = UserName{}
	typeOfUserName  = reflect.TypeOf(valueOfUserName)

	_                       = valueOfUserName.First
	fieldOfUserNameFirst, _ = typeOfUserName.FieldByName("First")
	tagOfUserNameFirst      = fieldOfUserNameFirst.Tag

	_                      = valueOfUserName.Last
	fieldOfUserNameLast, _ = typeOfUserName.FieldByName("Last")
	tagOfUserNameLast      = fieldOfUserNameLast.Tag
)

type UserNameTags struct {
	First string
	Last  string
}

func (UserName) Tags(tag string) UserNameTags {
	return UserNameTags{
		First: tagOfUserNameFirst.Get(tag),
		Last:  tagOfUserNameLast.Get(tag),
	}
}

func (v UserName) TagsBson() UserNameTags {
	return v.Tags("bson")
}

func (v UserName) TagsJson() UserNameTags {
	return v.Tags("json")
}
